[Eddie02]
url = "https://eddie02.ferbos-dev.com/api/states"
token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0N2VhMzBiMDMyNmI0NDM4ODczZDg4ZGI1NmJiYWNhZSIsImlhdCI6MTc0Mjc4NzE3MywiZXhwIjoyMDU4MTQ3MTczfQ.efziu1ODUbIFKmgDu4nKRTY4kKbAWSc5Z9P6gemsJAM"

[EddieMawar7]
url = "https://eddiemawar7.ferbos-dev.com/api/states"
token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZjgyYzMzMGEwYWI0MjU2YmZhNzJiYmNmNzY1MTY4MyIsImlhdCI6MTc0Mjc4MjU3MSwiZXhwIjoyMDU4MTQyNTcxfQ.tLVatxGbi42TauDe_SiE5u__6OxKEFMbTLrrmsHGnZM"