[Eddie02]
url = "https://eddie02.ferbos-dev.com"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0N2VhMzBiMDMyNmI0NDM4ODczZDg4ZGI1NmJiYWNhZSIsImlhdCI6MTc0Mjc4NzE3MywiZXhwIjoyMDU4MTQ3MTczfQ.efziu1ODUbIFKmgDu4nKRTY4kKbAWSc5Z9P6gemsJAM"

[Mawar7]
url = "https://eddiemawar7.ferbos-dev.com"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZjgyYzMzMGEwYWI0MjU2YmZhNzJiYmNmNzY1MTY4MyIsImlhdCI6MTc0Mjc4MjU3MSwiZXhwIjoyMDU4MTQyNTcxfQ.tLVatxGbi42TauDe_SiE5u__6OxKEFMbTLrrmsHGnZM"

[HajiNawi]
url = "https://eddiehajinawi.ferbos-dev.com"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjMzQzNWMxMThjMjI0ZWM4YTVlMGZkNGYxYzExM2QwOSIsImlhdCI6MTc0Mjg4NTE3NSwiZXhwIjoyMDU4MjQ1MTc1fQ.QaA0FgS7uQ4Oy-1LxIGaphT1Ig1lHDO2J21QFQV4oj4"

[Mawar8]
url = "https://mawar8eddie.ferbos-dev.com"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiYmZiZWEzNWQ1NzA0MmIxOWY1YjFiNzhjZTdkZDg0NiIsImlhdCI6MTc0Mjg4NTI0MCwiZXhwIjoyMDU4MjQ1MjQwfQ.6ZasJJ9WL1g-XyYFbQ2XWnDOjJOyrc-3J2wAB9Sc_v8"
